version: "3.8"
services:
  #  db:
  #    image: postgres:14.1
  #    restart: always
  #    environment:
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=postgres
  #    ports:
  #      - '5432:5432'
  #    volumes:
  #      - db:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
#  graphql-engine:
#    image: hasura/graphql-engine:v2.2.0
#    ports:
#      - "8080:8080"
#    depends_on:
#      - "db"
#    restart: always
#    environment:
#      ## postgres database to store Hasura metadata
#      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@db:5432/librematch_hasura
#      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
#      PG_DATABASE_URL: postgres://postgres:postgres@db:5432/librematch
#      ## enable the console served by server
#      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
#      ## enable debugging mode. It is recommended to disable this in production
#      HASURA_GRAPHQL_DEV_MODE: "true"
#      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
#      ## uncomment next line to set an admin secret
#      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db:
    driver: local
